// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lysgakfnypxavwnaetvg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5c2dha2ZueXB4YXZ3bmFldHZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1OTkwODIsImV4cCI6MjA2OTE3NTA4Mn0.tPByZ3aRK4thIFX18MT3dM0YRnFWGV4aDjGaheomaoE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});